# Predicting shots made per game by Kobe Bryant

In this lab you'll be using regularization techniques Ridge, Lasso, and Elastic Net to try and predict well how many shots Kobe Bryant made per game in his career.

---

### 1. Load packages and data

In [96]:
import numpy as np
import pandas as pd
import patsy

from sklearn.linear_model import Ridge, Lasso, ElasticNet, LinearRegression, RidgeCV, LassoCV, ElasticNetCV
from sklearn.cross_validation import cross_val_score

import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
plt.style.use('fivethirtyeight')

%config InlineBackend.figure_format = 'retina'
%matplotlib inline

In [97]:
kobe = pd.read_csv('/Users/austinwhaley/Desktop/DSI-SF-4/datasets/kobe_bryant/kobe_superwide_games.csv')

In [98]:
kobe.head()

SHOTS_MADE  AWAY_GAME  SEASON_OPPONENT:atl:1996-97  \
0         0.0          0                          0.0   
1         0.0          1                          0.0   
2         2.0          1                          0.0   
3         2.0          1                          0.0   
4         0.0          0                          1.0   

   SEASON_OPPONENT:atl:1997-98  SEASON_OPPONENT:atl:1999-00  \
0                          0.0                          0.0   
1                          0.0                          0.0   
2                          0.0                          0.0   
3                          0.0                          0.0   
4                          0.0                          0.0   

   SEASON_OPPONENT:atl:2000-01  SEASON_OPPONENT:atl:2001-02  \
0                          0.0                          0.0   
1                          0.0                          0.0   
2                          0.0                          0.0   
3                          0.0                          0.0   
4                          0.0                          0.0   

   SEASON_OPPONENT:atl:2002-03  SEASON_OPPONENT:atl:2003-04  \
0                          0.0                          0.0   
1                          0.0                          0.0   
2                          0.0                          0.0   
3                          0.0                          0.0   
4                          0.0                          0.0   

   SEASON_OPPONENT:atl:2004-05         ...          \
0                          0.0         ...           
1                          0.0         ...           
2                          0.0         ...           
3                          0.0         ...           
4                          0.0         ...           

   ACTION_TYPE:tip_layup_shot  ACTION_TYPE:tip_shot  \
0                         0.0                   0.0   
1                         0.0                   0.0   
2                         0.0                   0.0   
3                         0.0                   0.0   
4                         0.0                   0.0   

   ACTION_TYPE:turnaround_bank_shot  \
0                               0.0   
1                               0.0   
2                               0.0   
3                               0.0   
4                               0.0   

   ACTION_TYPE:turnaround_fadeaway_bank_jump_shot  \
0                                             0.0   
1                                             0.0   
2                                             0.0   
3                                             0.0   
4                                             0.0   

   ACTION_TYPE:turnaround_fadeaway_shot  \
0                                   0.0   
1                                   0.0   
2                                   0.0   
3                                   0.0   
4                                   0.0   

   ACTION_TYPE:turnaround_finger_roll_shot  ACTION_TYPE:turnaround_hook_shot  \
0                                      0.0                               0.0   
1                                      0.0                               0.0   
2                                      0.0                               0.0   
3                                      0.0                               0.0   
4                                      0.0                               0.0   

   ACTION_TYPE:turnaround_jump_shot  SEASON_GAME_NUMBER  CAREER_GAME_NUMBER  
0                               0.0                   1                   1  
1                               0.0                   2                   2  
2                               0.0                   3                   3  
3                               0.0                   4                   4  
4                               0.0                   5                   5  

[5 rows x 645 columns]

---

### 2. Examine the data

- How many columns are there?
- Infer what the observations (rows) and columns represent.
- Why is this data that regularization might be particularly useful for?

In [99]:
kobe.shape

(1558, 645)

---

### Make predictor and target variables. Normalize the predictors.

Why is normalization necessary for regularized regressions?

There is a class in sklearn.preprocessing called `StandardScaler`. Look it up and figure out how to use it to normalize your predictor matrix. 

In [100]:
from sklearn.preprocessing import StandardScaler MinMaxScaler #THIS IS THE SAME AS NORMALIZE = TRUE
                                    #STANDARDIZING #NORMALIZING
n_kobe = pd.DataFrame(StandardScaler().fit_transform(kobe), columns=kobe.columns)

In [102]:
X = kobe.drop('SHOTS_MADE', 1)
#X = n_kobe.drop('SHOTS_MADE', 1)
y = kobe['SHOTS_MADE']

---

### Build a linear regression predicting `SHOTS_MADE` from the rest of the columns.

Cross-validate the $R^2$ of a linear regression model with 10 cross-validation folds.

How does it perform?

In [103]:
lin_reg = LinearRegression(normalize=True)
lin_reg.fit(X, y)
lin_reg.predict(X)

array([ -0.484375,   0.140625,   0.8125  , ...,   8.546875,   4.03125 ,
        17.3125  ])

In [104]:
lin_reg.score(X, y)

0.77258002465554509

---

### Find an optimal value for Ridge regression alpha using RidgeCV

[Go to the documentation and read how RidgeCV works.](http://scikit-learn.org/stable/modules/generated/sklearn.linear_model.RidgeCV.html)

Hint: once the RidgeCV is fit, the attribute `.alpha_` contains the best alpha parameter it found through cross-validation.

Recall that Ridge performs best searching alphas through logarithmic space (`np.logspace`).


In [91]:
RidgeCV = RidgeCV()
RidgeCV.fit(X, y)
RidgeCV.predict(X)
#RidgeCV.alpha_

array([  0.09535994,  -0.09164382,   0.85705575, ...,   7.83287299,
         3.86867854,  17.09545819])

---

### Cross-validate the Ridge $R^2$ with the optimal alpha.

Is it better than the Linear regression? If so, why would this be?

In [92]:
print cross_val_score(RidgeCV ,X, y)

[ 0.69972936  0.54443452  0.51486863]


---

### Find an optimal value for Lasso regression alpha using LassoCV

[Go to the documentation and read how LassoCV works.](http://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LassoCV.html) It is very similar to RidgeCV.

Hint: again, once the LassoCV is fit, the attribute `.alpha_` contains the best alpha parameter it found through cross-validation.

Recall that Lasso, unlike Ridge, performs best searching alphas through linear space (`np.linspace`). However, you can actually let the LassoCV decide itself what alphas to use by instead setting the keyword argument `n_alphas=` to however many alphas you want it to search over.

In [73]:
LassoCV = LassoCV()
LassoCV.fit(X, y)
LassoCV.predict(X)
LassoCV.alpha_

0.080154358747570736

---

### Cross-validate the Lasso $R^2$ with the optimal alpha.

Is it better than the Linear regression? Is it better than Ridge? For each, why would this be?

Depending on which $R^2$ is better between the Ridge and Lasso, what can you infer about the primary issue in the data?

In [50]:
print cross_val_score(LassoCV ,X, y)

[ 0.72289919  0.5431591   0.51769028]


---

### Look at the coefficients for variables in the Lasso.

1. Show the coefficient for variables, ordered from largest to smallest coefficient by absolute value.
2. What percent of the variables in the original dataset are "zeroed-out" by the lasso?
3. What are the most important predictors for how many shots kobe made in a game?

Note: if you only fit the Lasso within cross_val_score, you will have to refit it outside of that
function to pull out the coefficients.

---

### Find an optimal value for Elastic Net regression alpha using ElasticNetCV

[Go to the documentation and read how LassoCV works.](http://scikit-learn.org/stable/modules/generated/sklearn.linear_model.ElasticNetCV.html).

Note here that you will be optimizing both the alpha parameter and the l1_ratio:

    alpha: strength of regularization
    l1_ratio: amount of ridge vs. lasso (0 = all ridge, 1 = all lasso)
    
Do not include 0 in the search for l1_ratio: it will not allow it and break!

You can use n_alphas for the alpha parameters instead of setting your own values: highly recommended!

Also - be careful setting too many l1_ratios over cross-validation folds in your search. It can take a very long time if you choose too many combinations and for the most part there are diminishing returns in this data.

In [93]:
l1_ratios = np.linspace(0.01, 1.0, 40)

In [94]:
ElasticNetCV = ElasticNetCV(l1_ratio=l1_ratios, n_alphas=150, verbose=1, n_jobs=-1, cv=5, normalize=True)
ElasticNetCV.fit(X, y)
ElasticNetCV.predict(X)
ElasticNetCV.alpha_

........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

0.0021520980133633875

---

### Cross-validate the ElasticNet $R^2$ with the optimal alpha and l1_ratio.

How does it compare to the other regularized regressions?

In [95]:
#print(cross_val_score(lasso, X, y)) 
print cross_val_score(ElasticNetCV ,X, y)

........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

[ 0.7240179   0.54134562  0.50991188]


---

### Plot the residuals for the ridge, lasso, and elastic net on histograms

This is another way to look at the performance of your model.

The tighter the distribution of residuals around zero, the better your model has performed!